import { Recipe } from 'src/app/features/about-product/models/recipe.model';
import { CookingLevel, Gender, PhysicalEffort } from '../enums/enums';
import { User } from 'src/app/features/profile/models/user.model';

export type FieldType = 'INPUT' | 'TEXTAREA' | 'SELECT' | 'MULTISELECT';
export default {
  Ingredients: [
    {
      IngredientID: 1,
      Name: 'Banana',
      Quantity: 2,
      Unit: 'pcs',
      PhotoURL: '../../../../../assets/fridge-icons/icons8-banana-96.png',
    },
    {
      IngredientID: 2,
      Name: 'Eggs',
      Quantity: 4,
      Unit: 'pcs',
      PhotoURL: '../../../../../assets/fridge-icons/icons8-eggs-64.png',
    },
    {
      IngredientID: 3,
      Name: 'Milk',
      Quantity: 1,
      Unit: 'L',
      PhotoURL: '../../../../../assets/fridge-icons/icons8-milk-96.png',
    },
    {
      IngredientID: 3,
      Name: 'Kiwi',
      Quantity: 3,
      Unit: 'pcs',
      PhotoURL: '../../../../../assets/fridge-icons/icons8-kiwi-64.png',
    },
    {
      IngredientID: 4,
      Name: 'Carrots',
      Quantity: 1,
      Unit: 'Kg',
      PhotoURL: '../../../../../assets/fridge-icons/carrots.png',
    },
    {
      IngredientID: 4,
      Name: 'Cheese',
      Quantity: 200,
      Unit: 'g',
      PhotoURL: '../../../../../assets/fridge-icons/icons8-cheese-64.png',
    },
    {
      IngredientID: 4,
      Name: 'Tomato',
      Quantity: 1,
      Unit: 'Kg',
      PhotoURL: '../../../../../assets/fridge-icons/icons8-tomato-64.png',
    },

    {
      IngredientID: 4,
      Name: 'Cabbage',
      Quantity: 1,
      Unit: 'pcs',
      PhotoURL: '../../../../../assets/fridge-icons/icons8-cabbage-64.png',
    },
    {
      IngredientID: 4,
      Name: 'Watermelon',
      Quantity: 1,
      Unit: 'pcs',
      PhotoURL: '../../../../../assets/fridge-icons/icons8-watermelon-96.png',
    },
    {
      IngredientID: 4,
      Name: 'Meat',
      Quantity: 2,
      Unit: 'Kg',
      PhotoURL: '../../../../../assets/fridge-icons/icons8-meat-80.png',
    },
    {
      IngredientID: 4,
      Name: 'Chicken',
      Quantity: 2,
      Unit: 'Kg',
      PhotoURL: '../../../../../assets/fridge-icons/icons8-chicken-64.png',
    },
    {
      IngredientID: 4,
      Name: 'Grapes',
      Quantity: 1,
      Unit: 'Kg',
      PhotoURL: '../../../../../assets/fridge-icons/icons8-grapes-64.png',
    },
    {
      IngredientID: 4,
      Name: 'Fish',
      Quantity: 2,
      Unit: 'pcs',
      PhotoURL: '../../../../../assets/fridge-icons/icons8-fish-96.png',
    },
    {
      IngredientID: 4,
      Name: 'Shrimp',
      Quantity: 2,
      Unit: 'pcs',
      PhotoURL: '../../../../../assets/fridge-icons/icons8-shrimp-96.png',
    },
    {
      IngredientID: 4,
      Name: 'Bacon',
      Quantity: 200,
      Unit: 'g',
      PhotoURL: '../../../../../assets/fridge-icons/icons8-bacon-58.png',
    },
    {
      IngredientID: 4,
      Name: 'Bread',
      Quantity: 500,
      Unit: 'g',
      PhotoURL: '../../../../../assets/fridge-icons/icons8-bread-64.png',
    },
  ],

  Recipes: [
    {
      RecipeID: 1,
      Name: 'Granola & Fruits bowl',
      PrepTime: 40,
      CookingLevel: CookingLevel.Beginner,
      Intructions: 'Lorem ipsum',
      CuisineID: 2,
      CuisineName: 'Italian',
      PhotoURL: '../../../assets/images/smoothie-bowl.jpg',
      Kcals: 1200,
      Favourites: 40,
    } as Recipe,
    {
      RecipeID: 2,
      Name: 'PoSkillet Polenta in Creamy Tomato Saucetato',
      PrepTime: 40,
      CookingLevel: CookingLevel.Intermediate,
      Intructions: 'Lorem ipsum',
      CuisineID: 2,
      CuisineName: 'Italian',
      PhotoURL: '../../../assets/images/recipes-1.jpg',
      Kcals: 1200,
      Favourites: 40,
    } as Recipe,
    {
      RecipeID: 3,
      Name: 'PoSkillet Polenta in Creamy Tomato Saucetato',
      PrepTime: 40,
      CookingLevel: CookingLevel.Intermediate,
      Intructions: 'Lorem ipsum',
      CuisineID: 2,
      CuisineName: 'Italian',
      PhotoURL: '../../../assets/images/lunch.jpg',
      Kcals: 1200,
      Favourites: 40,
    } as Recipe,
  ],

  User: {
    Id: 1,
    FirstName: 'Andreea',
    LastName: 'Apriotese',
    Email: 'andreea.apriotese11@gmail.com',
    Age: 22,
    Gender: Gender.F,
    Height: 162,
    Weight: 57,
    BMR: 2087,
    PhysicalEffort: PhysicalEffort.Sedentary,
    CookingLevel: CookingLevel.Intermediate,
    FavouriteCuisines: [
      '🍕Italian',
      '🍛Marocan',
      '🍔American',
      '🥓Barbecue',
      '🥕Kid-friendly',
      '🥐French',
      '🥗Greek',
    ],
    FollowedDiets: ['🥦Vegetarian', '🍗Paleo', '🐟Pescetarian'],
    DislikedIngredients: [
      'Eggs',
      'Fish',
      'Chilli paper',
      'Mushrooms',
      'Spinach',
    ],
    Goals: ['⭐Try new cuisines', '⭐Learn new cuisines', '⭐Save money'],
  } as User,
  Colors: [
    'zinc',
    'red',
    'orange',
    'yellow',
    'lime',
    'teal',
    'blue',
    'purple',
    'green',
    'fuchsia',
  ],

  Cuisines: [
    {
      id: 1,
      name: 'Italian',
      description: 'pasta, pizza, lasagna, risotto, focaccia',
      iconUrl: '../../../assets/icons/pizza-icon.png',
    },
    {
      id: 2,
      name: 'American',
      description: 'burgers, hot dogs, apple pie, barbecue ribs',
      iconUrl: '../../../assets/icons/hamburger-icon.png',
    },
    {
      id: 3,
      name: 'Kid-friendly',
      description: 'chicken parmesan, broccoli, chicken nuggets, noodle soup',
      iconUrl: '../../../assets/icons/kid-icon.png',
    },
    {
      id: 4,
      name: 'Mexican',
      description: 'tacos, burritos, nachos, guacamole, quesadillas',
      iconUrl: '../../../assets/icons/taco-icon.png',
    },
    {
      id: 5,
      name: 'French',
      description: 'foie gras, ratatouille, souffle, escargots, andouillette',
      iconUrl: '../../../assets/icons/croissant-icon.png',
    },
    {
      id: 6,
      name: 'Greek',
      description: 'moussaka, souvlaki, gyros, greek salad, papoutsakia',
      iconUrl: '../../../assets/icons/greek-icon.png',
    },
    {
      id: 7,
      name: 'Indian',
      description: 'samosa, dal, tandoori chicken, panipuri, kofta',
      iconUrl: '../../../assets/icons/india-icon.png',
    },
    {
      id: 8,
      name: 'Maroccan',
      description: 'couscous, zalouk, tagine, harira, saalouk',
      iconUrl: '../../../assets/icons/maroccan-icon.png',
    },
    {
      id: 9,
      name: 'Barbecue',
      description: 'BBQ pulled pork, kebabs, ribs, chicken skewers',
      iconUrl: '../../../assets/icons/barbecue-icon.png',
    },
    {
      id: 10,
      name: 'Chinese',
      description: 'kung pao chicken, mapo tofu, spring rolls, chow mein',
      iconUrl: '../../../assets/icons/chineese-icon.png',
    },
  ],
  Diets: [
    {
      id: 1,
      name: 'Vegan',
      description: '',
      iconUrl: '../../../assets/icons/vegan-icon.png',
    },
  
    {
      id: 2,
      name: 'Vegetarian',
      description: '',
      iconUrl: '../../../assets/icons/broccoli-icon.png',
    },
    {
      id: 3,
      name: 'Low fodmap',
      description: '',
      iconUrl: '../../../assets/icons/banana-icon.png',
    },
    
    {
      id: 4,
      name: 'Paleu',
      description: '',
      iconUrl: '../../../assets/icons/cashew-icon.png',
    },
    {
      id: 5,
      name: 'Pescetarian',
      description: '',
      iconUrl: '../../../assets/icons/fish-icon.png',
    },
    {
      id: 6,
      name: 'Ketogenic',
      description: '',
      iconUrl: '../../../assets/icons/steak-icon.png',
    },
  ],
};
